In [2]:
import pandas as pd

# Data inspection and cleaning

This notebook is used for initial inspection and preparation of the raw datasets for project.

The goal is composed of several objectives:
- inspect the available raw files
- understand their structure and year coverage
- identify the features relevant to the project
- begin initial cleaning(if neccessary) steps

In [13]:
# for easier execution

world_bank_path = r"C:\Users\User\Desktop\softuni lections\Data science\bulgaria_before_after_1989\data\raw\API_BGR_DS2_en_csv_v2_12004.csv"
nsi_population_path = r"C:\Users\User\Desktop\softuni lections\Data science\bulgaria_before_after_1989\data\raw\Pop_6.3_Census2011_EN.xlsx"

In [17]:
# loading of the main World Bank dataset

wb_raw = pd.read_csv(world_bank_path, skiprows = 4)
wb_raw.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Bulgaria,BGR,"Internally displaced persons, new displacement...",VC.IDP.NWDS,NaN,NaN,NaN,NaN,NaN,NaN,...,22.000000,50.000000,NaN,NaN,25.000000,900.000000,250.000000,NaN,NaN,NaN
1,Bulgaria,BGR,Transport services (% of commercial service ex...,TX.VAL.TRAN.ZS.WT,NaN,NaN,NaN,NaN,NaN,NaN,...,21.982555,21.523882,20.371885,27.588725,25.632471,23.130965,20.573738,15.294917,NaN,NaN
2,Bulgaria,BGR,"Computer, communications and other services (%...",TX.VAL.OTHR.ZS.WT,NaN,NaN,NaN,NaN,NaN,NaN,...,27.819322,30.468714,35.602935,45.740777,47.225617,46.585694,49.500847,53.292713,NaN,NaN
3,Bulgaria,BGR,"Merchandise exports by the reporting economy, ...",TX.VAL.MRCH.RS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001152,0.000569,0.000752,0.000405,0.000602,0.001418,0.006864,NaN,NaN,NaN
4,Bulgaria,BGR,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.R3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.570555,0.554189,0.557143,0.522498,0.581835,0.582724,0.568542,NaN,NaN,NaN

The World Bank file is structured so that each row represents a different indicator for Bulgaria, while the years are stored as columns. This means the dataset is initially in a wide format and will likely need reshaping before analysis.

In [19]:
# inspection of indicators and their respective codes and a duplicate check

wb_raw[["Indicator Name", "Indicator Code"]].drop_duplicates()

                                         Indicator Name     Indicator Code
0     Internally displaced persons, new displacement...        VC.IDP.NWDS
1     Transport services (% of commercial service ex...  TX.VAL.TRAN.ZS.WT
2     Computer, communications and other services (%...  TX.VAL.OTHR.ZS.WT
3     Merchandise exports by the reporting economy, ...  TX.VAL.MRCH.RS.ZS
4     Merchandise exports to low- and middle-income ...  TX.VAL.MRCH.R3.ZS
...                                                 ...                ...
1481  Net bilateral aid flows from DAC donors, Nethe...     DC.DAC.NLDL.CD
1482  Net bilateral aid flows from DAC donors, Japan...     DC.DAC.JPNL.CD
1483  Net bilateral aid flows from DAC donors, Hunga...     DC.DAC.HUNL.CD
1484  Net bilateral aid flows from DAC donors, Finla...     DC.DAC.FINL.CD
1485  Net bilateral aid flows from DAC donors, Germa...     DC.DAC.DEUL.CD

[1486 rows x 2 columns]

Because of the need of only several indicators for this project, searching for the desired ones will be made.

In [23]:
wb_raw[wb_raw["Indicator Name"].str.contains("Population, total", case=False, na=False)][["Indicator Name", "Indicator Code"]].drop_duplicates()

        Indicator Name Indicator Code
421  Population, total    SP.POP.TOTL

In [26]:
wb_raw[wb_raw["Indicator Name"].str.contains("Fertility rate, total", case=False, na=False)][["Indicator Name", "Indicator Code"]].drop_duplicates()

                               Indicator Name  Indicator Code
247  Fertility rate, total (births per woman)  SP.DYN.TFRT.IN

In [30]:
wb_raw[wb_raw["Indicator Name"].str.contains("Mortality rate, infant", case=False, na=False)][["Indicator Name", "Indicator Code"]].drop_duplicates()

                                        Indicator Name     Indicator Code
45   Mortality rate, infant, female (per 1,000 live...  SP.DYN.IMRT.FE.IN
248  Mortality rate, infant, male (per 1,000 live b...  SP.DYN.IMRT.MA.IN
439     Mortality rate, infant (per 1,000 live births)     SP.DYN.IMRT.IN

In [31]:
wb_raw[wb_raw["Indicator Name"].str.contains("Life expectancy", case=False, na=False)][["Indicator Name", "Indicator Code"]].drop_duplicates()

                               Indicator Name     Indicator Code
44    Life expectancy at birth, total (years)     SP.DYN.LE00.IN
438    Life expectancy at birth, male (years)  SP.DYN.LE00.MA.IN
987  Life expectancy at birth, female (years)  SP.DYN.LE00.FE.IN

In [34]:
# use the indicator codes to keep only the variables needed for the project
selected_indicator_codes = [
    "SP.POP.TOTL",
    "SP.DYN.TFRT.IN",
    "SP.DYN.IMRT.IN",
    "SP.DYN.LE00.IN"
]

wb_selected = wb_raw[wb_raw["Indicator Code"].isin(selected_indicator_codes)]

wb_selected[["Indicator Name", "Indicator Code"]]

                                     Indicator Name  Indicator Code
44          Life expectancy at birth, total (years)  SP.DYN.LE00.IN
247        Fertility rate, total (births per woman)  SP.DYN.TFRT.IN
421                               Population, total     SP.POP.TOTL
439  Mortality rate, infant (per 1,000 live births)  SP.DYN.IMRT.IN

In [38]:
wb_selected.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 'Unnamed: 70']

In [39]:
wb_selected.shape

(4, 71)

In [40]:
wb_selected.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
44,Bulgaria,BGR,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,6.924756e+01,7.019561e+01,6.949195e+01,7.030927e+01,7.112122e+01,7.129390e+01,...,7.481463e+01,7.496341e+01,7.511220e+01,7.335610e+01,7.121220e+01,7.416098e+01,7.575610e+01,7.576098e+01,NaN,NaN
247,Bulgaria,BGR,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.310000e+00,2.290000e+00,2.240000e+00,2.210000e+00,2.190000e+00,2.090000e+00,...,1.710000e+00,1.730000e+00,1.790000e+00,1.770000e+00,1.800000e+00,1.780000e+00,1.810000e+00,1.720000e+00,NaN,NaN
421,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,8.204168e+06,...,6.803468e+06,6.710798e+06,6.616726e+06,6.550696e+06,6.507301e+06,6.465097e+06,6.446596e+06,6.441421e+06,NaN,NaN
439,Bulgaria,BGR,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,4.490000e+01,4.040000e+01,3.680000e+01,3.420000e+01,3.240000e+01,3.140000e+01,...,6.100000e+00,5.800000e+00,5.500000e+00,5.300000e+00,5.200000e+00,5.000000e+00,4.800000e+00,4.600000e+00,NaN,NaN

## Observations after filtering the selected indicators

The filtered World Bank data now contains only the four indicators relevant to the project.
The dataset is still in wide format: rows represent indicators and columns represent years, which is an issue that will be going to addressed. 
There is also one extra unnamed column that appears to be empty and should be removed.

In [41]:
# removal of empty extra column

wb_selected = wb_selected.loc[:, ~wb_selected.columns.str.contains("^Unnamed")]
wb_selected.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
44,Bulgaria,BGR,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,6.924756e+01,7.019561e+01,6.949195e+01,7.030927e+01,7.112122e+01,7.129390e+01,...,7.481220e+01,7.481463e+01,7.496341e+01,7.511220e+01,7.335610e+01,7.121220e+01,7.416098e+01,7.575610e+01,7.576098e+01,NaN
247,Bulgaria,BGR,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.310000e+00,2.290000e+00,2.240000e+00,2.210000e+00,2.190000e+00,2.090000e+00,...,1.670000e+00,1.710000e+00,1.730000e+00,1.790000e+00,1.770000e+00,1.800000e+00,1.780000e+00,1.810000e+00,1.720000e+00,NaN
421,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,8.204168e+06,...,6.894139e+06,6.803468e+06,6.710798e+06,6.616726e+06,6.550696e+06,6.507301e+06,6.465097e+06,6.446596e+06,6.441421e+06,NaN
439,Bulgaria,BGR,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,4.490000e+01,4.040000e+01,3.680000e+01,3.420000e+01,3.240000e+01,3.140000e+01,...,6.400000e+00,6.100000e+00,5.800000e+00,5.500000e+00,5.300000e+00,5.200000e+00,5.000000e+00,4.800000e+00,4.600000e+00,NaN

In [42]:
# checking data types

wb_selected.dtypes.head(10)

Country Name          str
Country Code          str
Indicator Name        str
Indicator Code        str
1960              float64
1961              float64
1962              float64
1963              float64
1964              float64
1965              float64
dtype: object

In [43]:
#improving number display

pd.options.display.float_format = "{:,.2f}".format
wb_selected.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
44,Bulgaria,BGR,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,69.25,70.20,69.49,70.31,71.12,71.29,...,74.81,74.81,74.96,75.11,73.36,71.21,74.16,75.76,75.76,NaN
247,Bulgaria,BGR,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.31,2.29,2.24,2.21,2.19,2.09,...,1.67,1.71,1.73,1.79,1.77,1.80,1.78,1.81,1.72,NaN
421,Bulgaria,BGR,"Population, total",SP.POP.TOTL,"7,867,374.00","7,943,118.00","8,012,946.00","8,078,145.00","8,144,340.00","8,204,168.00",...,"6,894,139.00","6,803,468.00","6,710,798.00","6,616,726.00","6,550,696.00","6,507,301.00","6,465,097.00","6,446,596.00","6,441,421.00",NaN
439,Bulgaria,BGR,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,44.90,40.40,36.80,34.20,32.40,31.40,...,6.40,6.10,5.80,5.50,5.30,5.20,5.00,4.80,4.60,NaN

In [46]:
#check of years in the dataset
wb_selected.columns.tolist()[-10:]

['2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024']

In [53]:
#removing features of no use for the project

wb_selected_cleaned = wb_selected.drop(columns=["Country Name", "Country Code"])
wb_selected_cleaned.head()

,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
44,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,69.25,70.20,69.49,70.31,71.12,71.29,71.22,70.41,...,74.61,74.81,74.81,74.96,75.11,73.36,71.21,74.16,75.76,75.76
247,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.31,2.29,2.24,2.21,2.19,2.09,2.03,2.02,...,1.64,1.67,1.71,1.73,1.79,1.77,1.80,1.78,1.81,1.72
421,"Population, total",SP.POP.TOTL,"7,867,374.00","7,943,118.00","8,012,946.00","8,078,145.00","8,144,340.00","8,204,168.00","8,258,057.00","8,310,226.00",...,"6,984,225.00","6,894,139.00","6,803,468.00","6,710,798.00","6,616,726.00","6,550,696.00","6,507,301.00","6,465,097.00","6,446,596.00","6,441,421.00"
439,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,44.90,40.40,36.80,34.20,32.40,31.40,31.10,30.90,...,6.80,6.40,6.10,5.80,5.50,5.30,5.20,5.00,4.80,4.60